services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: askeep
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

ai:
  server:
    base-url: http://ai-server:8000